### PR TITLE
Update sbank-balance

### PR DESCRIPTION
**Pull request by CJCShadowsan**
Fix account flag inside SBATCH

### CODE REVIEW

**Comment by jcftang** [comment]
@paddydoyle care to comment on this one? I'm currently not using this right now can you verify this fix.

**Comment by paddydoyle** [comment]
Funnily enough '#SBATCH -U acc' seems to work as well, even though the man page says it should be '-A acc'. Maybe it's a backwards compatibility thing.

So yeah, good spot. LGTM.

**Comment by paddydoyle** [comment]
@jcftang  it looks like our branches have diverged a bit.. I can't automatically merge.

@CJCShadowsan Jimmy doesn't actively develop this any more and my branch is more up to date. In fact de9e812 looks very similar to your PR #5 and that's probably the cause of the merge conflict. It probably makes more sense for you to fork from my version?

@jcftang are you ok with that?

**Comment by jcftang** [comment]
I'd prefer to keep it maintained in one master repo, there seems to be a few people using it, I took a look at the diff of the different repos, it looks possible to merge it  all into one place.

**Comment by jcftang** [comment]
the formatting is a bit different between the two branches though, seeing cluster changes is more useful, adding in the admin level into the @CJCShadowsan changes makes more sense I think, it will break either way for people relying on either types of formatting.

this is one of those things where a re-write and more thinking about how it should work would be  a good thing

**Comment by paddydoyle** [comment]
@jcftang ok grand.

Yeah the change to show the AdminLevel was a bug on my part; it was copied from the 'sbank user list' code (I updated that bit to show longer names as well).

I've just made #7 to push my changes back upstream.

**Pull request merged**
